import type { SeoService } from "./types"

export const seoServices: SeoService[] = [
  {
    slug: "hemstadning",
    serviceType: "HomeCleaning",
    name: {
      sv: "Hemstädning",
      en: "Home cleaning",
      uk: "Прибирання дому",
      ru: "Уборка дома",
      pl: "Sprzątanie domu",
    },
    shortName: {
      sv: "Hemstädning",
      en: "Home cleaning",
      uk: "Дім",
      ru: "Дом",
      pl: "Dom",
    },
  },
  {
    slug: "flyttstadning",
    serviceType: "MoveOutCleaning",
    name: {
      sv: "Flyttstädning",
      en: "Move-out cleaning",
      uk: "Прибирання після переїзду",
      ru: "Уборка после переезда",
      pl: "Sprzątanie po przeprowadzce",
    },
    shortName: {
      sv: "Flyttstädning",
      en: "Move-out",
      uk: "Переїзд",
      ru: "Переезд",
      pl: "Przeprowadzka",
    },
  },
  {
    slug: "kontorsstadning",
    serviceType: "OfficeCleaning",
    name: {
      sv: "Kontorsstädning",
      en: "Office cleaning",
      uk: "Прибирання офісів",
      ru: "Уборка офисов",
      pl: "Sprzątanie biur",
    },
    shortName: {
      sv: "Kontor",
      en: "Office",
      uk: "Офіс",
      ru: "Офис",
      pl: "Biuro",
    },
  },
  {
    slug: "fonsterputs",
    serviceType: "WindowCleaning",
    name: {
      sv: "Fönsterputs",
      en: "Window cleaning",
      uk: "Миття вікон",
      ru: "Мойка окон",
      pl: "Mycie okien",
    },
    shortName: {
      sv: "Fönster",
      en: "Windows",
      uk: "Вікна",
      ru: "Окна",
      pl: "Okna",
    },
  },
  {
    slug: "trappstadning",
    serviceType: "StairwellCleaning",
    name: {
      sv: "Trappstädning",
      en: "Stairwell cleaning",
      uk: "Прибирання сходових кліток",
      ru: "Уборка лестничных клеток",
      pl: "Sprzątanie klatek schodowych",
    },
    shortName: {
      sv: "Trappor",
      en: "Stairwells",
      uk: "Сходи",
      ru: "Лестницы",
      pl: "Klatki",
    },
  },
  {
    slug: "byggstadning",
    serviceType: "ConstructionCleaning",
    name: {
      sv: "Byggstädning",
      en: "Construction cleaning",
      uk: "Будівельне прибирання",
      ru: "Строительная уборка",
      pl: "Sprzątanie po budowie",
    },
    shortName: {
      sv: "Bygg",
      en: "Construction",
      uk: "Будова",
      ru: "Стройка",
      pl: "Budowa",
    },
  },
  {
    slug: "storstadning",
    serviceType: "DeepCleaning",
    name: {
      sv: "Storstädning",
      en: "Deep cleaning",
      uk: "Генеральне прибирання",
      ru: "Генеральная уборка",
      pl: "Sprzątanie generalne",
    },
    shortName: {
      sv: "Storstädning",
      en: "Deep cleaning",
      uk: "Генеральне",
      ru: "Генеральная",
      pl: "Generalne",
    },
  },
  {
    slug: "dodsbo-stadning",
    serviceType: "EstateCleaning",
    name: {
      sv: "Dödsbostädning",
      en: "Estate cleaning",
      uk: "Прибирання спадкового житла",
      ru: "Уборка наследственного жилья",
      pl: "Sprzątanie mieszkania po zmarłym",
    },
    shortName: {
      sv: "Dödsbo",
      en: "Estate",
      uk: "Спадок",
      ru: "Наследство",
      pl: "Spadek",
    },
  },
  {
    slug: "visningsstadning",
    serviceType: "RealEstateCleaning",
    name: {
      sv: "Visningsstädning",
      en: "Viewing cleaning",
      uk: "Прибирання перед показом житла",
      ru: "Уборка перед показом жилья",
      pl: "Sprzątanie przed pokazem nieruchomości",
    },
    shortName: {
      sv: "Visning",
      en: "Viewing",
      uk: "Показ",
      ru: "Показ",
      pl: "Pokaz",
    },
  },
  {
    slug: "butiksstadning",
    serviceType: "StoreCleaning",
    name: {
      sv: "Butiksstädning",
      en: "Store cleaning",
      uk: "Прибирання магазинів",
      ru: "Уборка магазинов",
      pl: "Sprzątanie sklepów",
    },
    shortName: {
      sv: "Butik",
      en: "Store",
      uk: "Магазин",
      ru: "Магазин",
      pl: "Sklep",
    },
  },
  {
    slug: "restaurangstadning",
    serviceType: "RestaurantCleaning",
    name: {
      sv: "Restaurangstädning",
      en: "Restaurant cleaning",
      uk: "Прибирання ресторанів",
      ru: "Уборка ресторанов",
      pl: "Sprzątanie restauracji",
    },
    shortName: {
      sv: "Restaurang",
      en: "Restaurant",
      uk: "Ресторан",
      ru: "Ресторан",
      pl: "Restauracja",
    },
  },
  {
    slug: "hotellstadning",
    serviceType: "HotelCleaning",
    name: {
      sv: "Hotellstädning",
      en: "Hotel cleaning",
      uk: "Прибирання готелів",
      ru: "Уборка отелей",
      pl: "Sprzątanie hoteli",
    },
    shortName: {
      sv: "Hotell",
      en: "Hotel",
      uk: "Готель",
      ru: "Отель",
      pl: "Hotel",
    },
  },
  {
    slug: "skolstadning",
    serviceType: "SchoolCleaning",
    name: {
      sv: "Skolstädning",
      en: "School cleaning",
      uk: "Прибирання шкіл",
      ru: "Уборка школ",
      pl: "Sprzątanie szkół",
    },
    shortName: {
      sv: "Skola",
      en: "School",
      uk: "Школа",
      ru: "Школа",
      pl: "Szkoła",
    },
  },
  {
    slug: "vardstadning",
    serviceType: "HealthcareCleaning",
    name: {
      sv: "Vårdstädning",
      en: "Healthcare cleaning",
      uk: "Прибирання медичних приміщень",
      ru: "Уборка медицинских помещений",
      pl: "Sprzątanie placówek medycznych",
    },
    shortName: {
      sv: "Vård",
      en: "Healthcare",
      uk: "Медицина",
      ru: "Медицина",
      pl: "Medyczne",
    },
  },
  {
    slug: "industristadning",
    serviceType: "IndustrialCleaning",
    name: {
      sv: "Industristädning",
      en: "Industrial cleaning",
      uk: "Промислове прибирання",
      ru: "Промышленная уборка",
      pl: "Sprzątanie przemysłowe",
    },
    shortName: {
      sv: "Industri",
      en: "Industrial",
      uk: "Промислове",
      ru: "Промышленная",
      pl: "Przemysł",
    },
  },
  {
    slug: "garage-stadning",
    serviceType: "GarageCleaning",
    name: {
      sv: "Garagestädning",
      en: "Garage cleaning",
      uk: "Прибирання гаражів",
      ru: "Уборка гаражей",
      pl: "Sprzątanie garaży",
    },
    shortName: {
      sv: "Garage",
      en: "Garage",
      uk: "Гараж",
      ru: "Гараж",
      pl: "Garaż",
    },
  },
  {
    slug: "golvvard",
    serviceType: "FloorCare",
    name: {
      sv: "Golvvård",
      en: "Floor care",
      uk: "Догляд за підлогою",
      ru: "Уход за полом",
      pl: "Pielęgnacja podłóg",
    },
    shortName: {
      sv: "Golvvård",
      en: "Floors",
      uk: "Підлога",
      ru: "Пол",
      pl: "Podłogi",
    },
  },
  {
    slug: "mattvatt",
    serviceType: "CarpetCleaning",
    name: {
      sv: "Mattvätt",
      en: "Carpet cleaning",
      uk: "Чистка килимів",
      ru: "Чистка ковров",
      pl: "Pranie dywanów",
    },
    shortName: {
      sv: "Mattvätt",
      en: "Carpets",
      uk: "Килими",
      ru: "Ковры",
      pl: "Dywany",
    },
  },
  {
    slug: "sofftvatt",
    serviceType: "UpholsteryCleaning",
    name: {
      sv: "Sofftvätt",
      en: "Sofa cleaning",
      uk: "Чистка диванів",
      ru: "Чистка диванов",
      pl: "Czyszczenie sof",
    },
    shortName: {
      sv: "Sofftvätt",
      en: "Sofas",
      uk: "Дивани",
      ru: "Диваны",
      pl: "Sofy",
    },
  },
  {
    slug: "sanering",
    serviceType: "Sanitization",
    name: {
      sv: "Sanering",
      en: "Sanitization",
      uk: "Санітарна обробка",
      ru: "Санитарная обработка",
      pl: "Dezynfekcja",
    },
    shortName: {
      sv: "Sanering",
      en: "Sanitization",
      uk: "Санітарія",
      ru: "Санобработка",
      pl: "Dezynfekcja",
    },
  },
]