
import type { Locale } from "@/lib/i18n"
import type { CrmCustomerStage } from "./types"

export type CrmCopy = {
  eyebrow: string
  title: string
  subtitle: string
  customers: string
  customer: string
  total: string
  prospects: string
  activeCustomers: string
  vipCustomers: string
  followUpsDue: string
  lifetimeRevenue: string
  searchPlaceholder: string
  allStages: string
  allTags: string
  allFollowUps: string
  dueFollowUps: string
  upcomingFollowUps: string
  sortRecent: string
  sortName: string
  sortValue: string
  sortFollowUp: string
  filter: string
  reset: string
  noCustomersTitle: string
  noCustomersText: string
  openCustomer: string
  leads: string
  bookings: string
  completed: string
  revenue: string
  lastActivity: string
  followUp: string
  tags: string
  stage: string
  company: string
  email: string
  phone: string
  city: string
  firstSeen: string
  lastSeen: string
  notes: string
  save: string
  saved: string
  saveError: string
  back: string
  contact: string
  call: string
  sendEmail: string
  customerHistory: string
  leadHistory: string
  bookingHistory: string
  activity: string
  noActivity: string
  noLeads: string
  noBookings: string
  status: string
  service: string
  value: string
  date: string
  source: string
  openLead: string
  openBooking: string
  profile: string
  upcoming: string
  completedBookings: string
  customerValue: string
  editCustomer: string
  tagsHint: string
  followUpHint: string
  stages: Record<CrmCustomerStage, string>
  event_customer_created: string
  event_contact_updated: string
  event_lifecycle_changed: string
  event_tags_updated: string
  event_notes_updated: string
  event_follow_up_changed: string
}

export const crmCopy: Record<Locale, CrmCopy> = {
  sv: {
    eyebrow: "CRM Lite",
    title: "Kunder",
    subtitle: "En samlad kundbas från leads och bokningar med historik, uppföljningar, taggar och kundvärde.",
    customers: "Kunder",
    customer: "Kund",
    total: "Totalt",
    prospects: "Prospekt",
    activeCustomers: "Kunder",
    vipCustomers: "VIP",
    followUpsDue: "Uppföljning förfallen",
    lifetimeRevenue: "Genomfört kundvärde",
    searchPlaceholder: "Namn, e-post, telefon eller ort",
    allStages: "Alla stadier",
    allTags: "Alla taggar",
    allFollowUps: "Alla uppföljningar",
    dueFollowUps: "Förfallna uppföljningar",
    upcomingFollowUps: "Kommande uppföljningar",
    sortRecent: "Senast aktiv",
    sortName: "Namn A–Ö",
    sortValue: "Högst värde",
    sortFollowUp: "Närmaste uppföljning",
    filter: "Filtrera",
    reset: "Återställ",
    noCustomersTitle: "Inga kunder ännu",
    noCustomersText: "Kundbasen byggs automatiskt när företaget får leads eller bokningar.",
    openCustomer: "Öppna kund",
    leads: "Leads",
    bookings: "Bokningar",
    completed: "Klara",
    revenue: "Värde",
    lastActivity: "Senaste aktivitet",
    followUp: "Följ upp",
    tags: "Taggar",
    stage: "Kundstadium",
    company: "Företag",
    email: "E-post",
    phone: "Telefon",
    city: "Ort",
    firstSeen: "Första kontakt",
    lastSeen: "Senast sedd",
    notes: "Interna kundanteckningar",
    save: "Spara kund",
    saved: "Kunden har sparats.",
    saveError: "Kunden kunde inte sparas.",
    back: "Till kunder",
    contact: "Kontakt",
    call: "Ring",
    sendEmail: "Skicka e-post",
    customerHistory: "Kundhistorik",
    leadHistory: "Lead-historik",
    bookingHistory: "Bokningshistorik",
    activity: "Aktivitet",
    noActivity: "Ingen aktivitet ännu.",
    noLeads: "Inga leads för kunden.",
    noBookings: "Inga bokningar för kunden.",
    status: "Status",
    service: "Tjänst",
    value: "Värde",
    date: "Datum",
    source: "Källa",
    openLead: "Öppna lead",
    openBooking: "Öppna bokning",
    profile: "Kundprofil",
    upcoming: "Kommande",
    completedBookings: "Klara bokningar",
    customerValue: "Kundvärde",
    editCustomer: "Kundhantering",
    tagsHint: "Separera taggar med kommatecken, till exempel: återkommande, privat, VIP.",
    followUpHint: "Använd uppföljning för nästa samtal, offert eller återkontakt.",
    stages: { prospect: "Prospekt", customer: "Kund", vip: "VIP", inactive: "Inaktiv" },
    event_customer_created: "Kund skapad",
    event_contact_updated: "Kontaktuppgifter uppdaterades",
    event_lifecycle_changed: "Kundstadium ändrades",
    event_tags_updated: "Taggar uppdaterades",
    event_notes_updated: "Anteckningar uppdaterades",
    event_follow_up_changed: "Uppföljning ändrades",
  },
  en: {
    eyebrow: "CRM Lite",
    title: "Customers",
    subtitle: "A unified customer base built from leads and bookings, with history, follow-ups, tags and customer value.",
    customers: "Customers",
    customer: "Customer",
    total: "Total",
    prospects: "Prospects",
    activeCustomers: "Customers",
    vipCustomers: "VIP",
    followUpsDue: "Follow-ups due",
    lifetimeRevenue: "Completed customer value",
    searchPlaceholder: "Name, email, phone or city",
    allStages: "All stages",
    allTags: "All tags",
    allFollowUps: "All follow-ups",
    dueFollowUps: "Due follow-ups",
    upcomingFollowUps: "Upcoming follow-ups",
    sortRecent: "Last active",
    sortName: "Name A–Z",
    sortValue: "Highest value",
    sortFollowUp: "Nearest follow-up",
    filter: "Filter",
    reset: "Reset",
    noCustomersTitle: "No customers yet",
    noCustomersText: "The customer base is created automatically when the company receives leads or bookings.",
    openCustomer: "Open customer",
    leads: "Leads",
    bookings: "Bookings",
    completed: "Completed",
    revenue: "Value",
    lastActivity: "Last activity",
    followUp: "Follow up",
    tags: "Tags",
    stage: "Customer stage",
    company: "Company",
    email: "Email",
    phone: "Phone",
    city: "City",
    firstSeen: "First contact",
    lastSeen: "Last seen",
    notes: "Internal customer notes",
    save: "Save customer",
    saved: "Customer saved.",
    saveError: "Customer could not be saved.",
    back: "Back to customers",
    contact: "Contact",
    call: "Call",
    sendEmail: "Send email",
    customerHistory: "Customer history",
    leadHistory: "Lead history",
    bookingHistory: "Booking history",
    activity: "Activity",
    noActivity: "No activity yet.",
    noLeads: "No leads for this customer.",
    noBookings: "No bookings for this customer.",
    status: "Status",
    service: "Service",
    value: "Value",
    date: "Date",
    source: "Source",
    openLead: "Open lead",
    openBooking: "Open booking",
    profile: "Customer profile",
    upcoming: "Upcoming",
    completedBookings: "Completed bookings",
    customerValue: "Customer value",
    editCustomer: "Customer management",
    tagsHint: "Separate tags with commas, for example: recurring, private, VIP.",
    followUpHint: "Use follow-up for the next call, quote or customer check-in.",
    stages: { prospect: "Prospect", customer: "Customer", vip: "VIP", inactive: "Inactive" },
    event_customer_created: "Customer created",
    event_contact_updated: "Contact details updated",
    event_lifecycle_changed: "Customer stage changed",
    event_tags_updated: "Tags updated",
    event_notes_updated: "Notes updated",
    event_follow_up_changed: "Follow-up changed",
  },
  uk: {
    eyebrow: "CRM Lite",
    title: "Клієнти",
    subtitle: "Єдина клієнтська база з лідів і бронювань: історія, follow-up, теги та вартість клієнта.",
    customers: "Клієнти",
    customer: "Клієнт",
    total: "Усього",
    prospects: "Потенційні",
    activeCustomers: "Клієнти",
    vipCustomers: "VIP",
    followUpsDue: "Прострочені follow-up",
    lifetimeRevenue: "Вартість завершених робіт",
    searchPlaceholder: "Ім’я, email, телефон або місто",
    allStages: "Усі стадії",
    allTags: "Усі теги",
    allFollowUps: "Усі follow-up",
    dueFollowUps: "Прострочені follow-up",
    upcomingFollowUps: "Майбутні follow-up",
    sortRecent: "Остання активність",
    sortName: "Ім’я А–Я",
    sortValue: "Найвища вартість",
    sortFollowUp: "Найближчий follow-up",
    filter: "Фільтрувати",
    reset: "Скинути",
    noCustomersTitle: "Клієнтів поки немає",
    noCustomersText: "Клієнтська база створюється автоматично, коли компанія отримує ліди або бронювання.",
    openCustomer: "Відкрити клієнта",
    leads: "Ліди",
    bookings: "Бронювання",
    completed: "Завершено",
    revenue: "Вартість",
    lastActivity: "Остання активність",
    followUp: "Follow-up",
    tags: "Теги",
    stage: "Стадія клієнта",
    company: "Компанія",
    email: "Email",
    phone: "Телефон",
    city: "Місто",
    firstSeen: "Перший контакт",
    lastSeen: "Останній контакт",
    notes: "Внутрішні нотатки про клієнта",
    save: "Зберегти клієнта",
    saved: "Клієнта збережено.",
    saveError: "Не вдалося зберегти клієнта.",
    back: "До клієнтів",
    contact: "Контакт",
    call: "Подзвонити",
    sendEmail: "Надіслати email",
    customerHistory: "Історія клієнта",
    leadHistory: "Історія лідів",
    bookingHistory: "Історія бронювань",
    activity: "Активність",
    noActivity: "Активності поки немає.",
    noLeads: "У цього клієнта немає лідів.",
    noBookings: "У цього клієнта немає бронювань.",
    status: "Статус",
    service: "Послуга",
    value: "Вартість",
    date: "Дата",
    source: "Джерело",
    openLead: "Відкрити лід",
    openBooking: "Відкрити бронювання",
    profile: "Профіль клієнта",
    upcoming: "Майбутні",
    completedBookings: "Завершені бронювання",
    customerValue: "Вартість клієнта",
    editCustomer: "Керування клієнтом",
    tagsHint: "Розділяйте теги комами, наприклад: регулярний, приватний, VIP.",
    followUpHint: "Використовуйте follow-up для наступного дзвінка, пропозиції або повторного контакту.",
    stages: { prospect: "Потенційний", customer: "Клієнт", vip: "VIP", inactive: "Неактивний" },
    event_customer_created: "Клієнта створено",
    event_contact_updated: "Контактні дані оновлено",
    event_lifecycle_changed: "Стадію клієнта змінено",
    event_tags_updated: "Теги оновлено",
    event_notes_updated: "Нотатки оновлено",
    event_follow_up_changed: "Follow-up змінено",
  },
  ru: {
    eyebrow: "CRM Lite",
    title: "Клиенты",
    subtitle: "Единая клиентская база из лидов и бронирований: история, follow-up, теги и ценность клиента.",
    customers: "Клиенты",
    customer: "Клиент",
    total: "Всего",
    prospects: "Потенциальные",
    activeCustomers: "Клиенты",
    vipCustomers: "VIP",
    followUpsDue: "Просроченные follow-up",
    lifetimeRevenue: "Стоимость завершённых работ",
    searchPlaceholder: "Имя, email, телефон или город",
    allStages: "Все стадии",
    allTags: "Все теги",
    allFollowUps: "Все follow-up",
    dueFollowUps: "Просроченные follow-up",
    upcomingFollowUps: "Будущие follow-up",
    sortRecent: "Последняя активность",
    sortName: "Имя А–Я",
    sortValue: "Наивысшая стоимость",
    sortFollowUp: "Ближайший follow-up",
    filter: "Фильтровать",
    reset: "Сбросить",
    noCustomersTitle: "Клиентов пока нет",
    noCustomersText: "Клиентская база создаётся автоматически, когда компания получает лиды или бронирования.",
    openCustomer: "Открыть клиента",
    leads: "Лиды",
    bookings: "Бронирования",
    completed: "Завершено",
    revenue: "Стоимость",
    lastActivity: "Последняя активность",
    followUp: "Follow-up",
    tags: "Теги",
    stage: "Стадия клиента",
    company: "Компания",
    email: "Email",
    phone: "Телефон",
    city: "Город",
    firstSeen: "Первый контакт",
    lastSeen: "Последний контакт",
    notes: "Внутренние заметки о клиенте",
    save: "Сохранить клиента",
    saved: "Клиент сохранён.",
    saveError: "Не удалось сохранить клиента.",
    back: "К клиентам",
    contact: "Контакт",
    call: "Позвонить",
    sendEmail: "Отправить email",
    customerHistory: "История клиента",
    leadHistory: "История лидов",
    bookingHistory: "История бронирований",
    activity: "Активность",
    noActivity: "Активности пока нет.",
    noLeads: "У этого клиента нет лидов.",
    noBookings: "У этого клиента нет бронирований.",
    status: "Статус",
    service: "Услуга",
    value: "Стоимость",
    date: "Дата",
    source: "Источник",
    openLead: "Открыть лид",
    openBooking: "Открыть бронирование",
    profile: "Профиль клиента",
    upcoming: "Предстоящие",
    completedBookings: "Завершённые бронирования",
    customerValue: "Ценность клиента",
    editCustomer: "Управление клиентом",
    tagsHint: "Разделяйте теги запятыми, например: регулярный, частный, VIP.",
    followUpHint: "Используйте follow-up для следующего звонка, предложения или повторного контакта.",
    stages: { prospect: "Потенциальный", customer: "Клиент", vip: "VIP", inactive: "Неактивный" },
    event_customer_created: "Клиент создан",
    event_contact_updated: "Контактные данные обновлены",
    event_lifecycle_changed: "Стадия клиента изменена",
    event_tags_updated: "Теги обновлены",
    event_notes_updated: "Заметки обновлены",
    event_follow_up_changed: "Follow-up изменён",
  },
  pl: {
    eyebrow: "CRM Lite",
    title: "Klienci",
    subtitle: "Jedna baza klientów z leadów i rezerwacji: historia, follow-up, tagi i wartość klienta.",
    customers: "Klienci",
    customer: "Klient",
    total: "Łącznie",
    prospects: "Potencjalni",
    activeCustomers: "Klienci",
    vipCustomers: "VIP",
    followUpsDue: "Zaległe follow-up",
    lifetimeRevenue: "Wartość zakończonych prac",
    searchPlaceholder: "Imię, email, telefon lub miasto",
    allStages: "Wszystkie etapy",
    allTags: "Wszystkie tagi",
    allFollowUps: "Wszystkie follow-up",
    dueFollowUps: "Zaległe follow-up",
    upcomingFollowUps: "Nadchodzące follow-up",
    sortRecent: "Ostatnia aktywność",
    sortName: "Nazwa A–Z",
    sortValue: "Najwyższa wartość",
    sortFollowUp: "Najbliższy follow-up",
    filter: "Filtruj",
    reset: "Resetuj",
    noCustomersTitle: "Brak klientów",
    noCustomersText: "Baza klientów powstaje automatycznie, gdy firma otrzymuje leady lub rezerwacje.",
    openCustomer: "Otwórz klienta",
    leads: "Leady",
    bookings: "Rezerwacje",
    completed: "Zakończone",
    revenue: "Wartość",
    lastActivity: "Ostatnia aktywność",
    followUp: "Follow-up",
    tags: "Tagi",
    stage: "Etap klienta",
    company: "Firma",
    email: "Email",
    phone: "Telefon",
    city: "Miasto",
    firstSeen: "Pierwszy kontakt",
    lastSeen: "Ostatni kontakt",
    notes: "Wewnętrzne notatki o kliencie",
    save: "Zapisz klienta",
    saved: "Klient zapisany.",
    saveError: "Nie udało się zapisać klienta.",
    back: "Do klientów",
    contact: "Kontakt",
    call: "Zadzwoń",
    sendEmail: "Wyślij email",
    customerHistory: "Historia klienta",
    leadHistory: "Historia leadów",
    bookingHistory: "Historia rezerwacji",
    activity: "Aktywność",
    noActivity: "Brak aktywności.",
    noLeads: "Brak leadów dla tego klienta.",
    noBookings: "Brak rezerwacji dla tego klienta.",
    status: "Status",
    service: "Usługa",
    value: "Wartość",
    date: "Data",
    source: "Źródło",
    openLead: "Otwórz lead",
    openBooking: "Otwórz rezerwację",
    profile: "Profil klienta",
    upcoming: "Nadchodzące",
    completedBookings: "Zakończone rezerwacje",
    customerValue: "Wartość klienta",
    editCustomer: "Zarządzanie klientem",
    tagsHint: "Oddzielaj tagi przecinkami, na przykład: cykliczny, prywatny, VIP.",
    followUpHint: "Użyj follow-up dla następnego telefonu, wyceny lub kontaktu z klientem.",
    stages: { prospect: "Potencjalny", customer: "Klient", vip: "VIP", inactive: "Nieaktywny" },
    event_customer_created: "Klient utworzony",
    event_contact_updated: "Dane kontaktowe zaktualizowane",
    event_lifecycle_changed: "Etap klienta zmieniony",
    event_tags_updated: "Tagi zaktualizowane",
    event_notes_updated: "Notatki zaktualizowane",
    event_follow_up_changed: "Follow-up zmieniony",
  },
}
